### PR TITLE
l10n: Add Indonesian translation

### PR DESCRIPTION
**Pull request by azrdn**
This PR adds Indonesian translation to the app

### CODE REVIEW

**Comment by huynhsontung** [comment]
Hello, was there any reason to close this PR?

**Comment by azrdn** [comment]
Hi @huynhsontung!
I saw you added my translations via crowdin, so i guess this pull request is not needed anymore, i'm happy to reopen this if you want to merge though.

**Comment by huynhsontung** [comment]
Thank you for your translation. I added your translation texts in Crowdin to keep the translation progress in sync with the repo. I wanted to merge this PR afterward, so your contribution is properly credited. Otherwise, I can link this PR in the [next Crowdin sync](https://github.com/huynhsontung/Screenbox/pull/320).

**Comment by azrdn** [comment]
Okay, i reopened it, thank you!

**Pull request merged**
