### PR TITLE
Minor design change to audio icons

### PR DESCRIPTION
**Pull request by United600**
Minor changes to the top panel shadows and added the record label.

### CODE REVIEW

**Comment by huynhsontung** [comment]
Looking solid! Let me know when you are ready to merge.

**Comment by United600** [comment]
> Looking solid! Let me know when you are ready to merge.

If you're happy with the icons go for it.

**Comment by United600** [comment]
Welp just noticed that for some reason the note is darker, must've merged with some transparency. Yikes.

**Comment by huynhsontung** [comment]
I made some adjustments to the icon paddings and the flag for sizes 256 and 512.

**Pull request merged**
